### ISSUE TITLE
Thema Regionaldienst, aka Wochenendbetreuung überdenken

### ISSUE THREAD

**Issue by dgorbach** [dgorbach/Vodamep#5]
Regionaldienst: Eine Mitarbeiterin betreut Klientinnen eines anderen Vereines. (Vor allem an Wochenenden, wennn der Stammverein keine Betreuung anbietet.)

Bisher erfolgt die Meldung der Leistungspunkte über den Verein, der die Leistung erbringt. Dazu wurde dort der Klient angelegt.

Dadurch fehlen diese Leistungen aber in der Dokumentation des Stammvereins und es können für diese Leistungen kein Selbstbehalt verrechnet werden. 

Ziel: Die Leistungen werden im Stammverein erfasst und von diesem gemeldet.

Die Stammdaten der Mitarbeiterin, die die Leistung erbringt, sind im Stammverein nicht erfasst. Ihre Identität ist bekannt.

Frage: Wie sollen diese Leistungen gemeldet werden?

**Comment by idicon** [comment]
Regionaldienst: einige KPVs schließen sich über das Wochenende zusammen (Regionalverbund) und können darum Leistungen an Wochenenden anbieten, das ist sehr klug und hier ist der Nutzen für alle sehr hoch. Die begrenzten personellen Ressourcen einzelner KPVs können für ihre Gemeinde einen Wochenenddienst nicht anbieten, wenn das aber regionalisiert wird ist das möglich. Die Leistungen sind an Wochenenden deutlich eingegrenzt und jeweils spez. Fallbezogen (hier muss man unbedingt am Samstag oder Sonntag eine Versorgung erfolgen). 
In Feldkirch sind so vier Vereine im Verbund (FK-Levis-Tisis, FK-Gisingen, FK-Nofels, FK-Tosters), weiters die KPVs Altach, Koblach-Mäder und Götzis. Weiters Hörbranz, Hohenweiler und Lochau. 
Lösung: Die Patienten die in Vertretung am Wochenende von einem anderen Verein betreut werden sind dort auch mit den Stammdaten erfasst. Leistungserfassung mittels Massnahme"Hausbesuch" und ggf. Bericht schreiben. 
Alle Vereine die Wochenendvertretungen machen: 
_Einrichten des Mandanten: Wochenendvertretung ? sinnvoll 

_Klärung: Erhebung des Pflegebeitrages?
